export const responsePostAuthUser = {
  result: {
    token: 'some-token-123',
    user: {
      _id: 'some-id-123',
      _key: 'test-1',
      username: 'test_1',
      email: 'test_1@example.com',
      roles: [{ _id: 'some-id-123', _type: 'role' }],
      profile: {
        name: 'User №1',
        surname: 'UserSurname1',
        phone: '+70000000001',
        middlename: '',
        avatar: {},
        birthday: '',
        position: '',
        country: {},
        city: {},
        street: '',
      },
      status: 'confirm',
      isNew: false,
      order: 3,
      proto: {},
      _type: 'user',
      dateCreate: '2023-12-12T09:54:05.202Z',
      dateUpdate: '2023-12-12T09:54:05.202Z',
      isDeleted: false,
    },
  },
};
